# 数据操作

首先导入`torch`，而不是`pytorch`

In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过`shape`属性来访问张量的形状和张量中元素的总数

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

可以使用`reshape`改变张量的形状，而不改变元素数量和元素值

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

全0、全1的数组

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过python列表(或嵌套列表list of lists)，创建张量

In [12]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

常见的+、-、\*、/、** element-wise运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [14]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [15]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [16]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [17]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [18]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [19]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连结在一起，catenate /ˈkætɪˌneɪt/ vt.连接

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [21]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算符构建二元张量

In [25]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中所有元素进行求和会产生一个只有一个元素的张量

In [29]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
X.sum()

tensor(66.)

形状不同的张量，可以通过广播机制（broadcasting mechanism），执行按元素操作(这里容易出错）

In [31]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

索引和切片

In [34]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [36]:
X[1: 3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能为新结果分配内存

In [38]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [40]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140232661833984
id(Z): 140232661833984


使用`X[:] = X + Y`或`X += Y`减少操作的内存开销

In [41]:
before = id(X)
X += Y
id(X) == before

True

转换为NumPy张量

In [1]:
# 这个步骤是不需要的，因为这里numpy是对象方法，而不是numpy模块
import numpy

In [44]:
X

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [45]:
A = X.numpy()
B = torch.tensor(A)

In [46]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

大小为1的张量转换为Python标量

In [3]:
a = torch.tensor([3.5])

In [4]:
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)